### ISSUE TITLE
version 5.7.0 - cannot access recordings

### ISSUE THREAD

**Issue by jan-panoch** [dciancu/unifi-protect-unvr-docker-arm64#54]
hello,
i tried to build news version, there is protect 6.0.47, recording of camera works - i see growing .ubv files in video directory,
i can see actual videostream from camera, but when i try to access recording, it doesn't work - i can scroll to previous time, but
i cannot see video..
it works with protect 5, i'm not sure, when it stop working - i upgraded to protect 6 and it works for some time.
but now - even if i setup complete new protect server (clean storage directory) it's the same..
maybe i try to compile some older version with protect 5 and check if it works still..
Jan

**Comment by tszyszko** [comment]
I seem to be seeing this too ever since updating from 6.0.47 to 6.1.68 using @dciancu build command above. Any snapshots taken before the update work fine, any since are broken :

2025-09-29T10:48:26.267Z I unifi-protect  -     WorkersPool::Enqueue pool Read task id=139 name=ubvFileListFragments starting now inprogress 1/4 [ubvFileListFragments=1 ] pending 0/200 [] [1]
2025-09-29T10:48:26.268Z E B_139  - IPCFileLock::TryLockFor, try lock failed Bad file descriptor [2]
2025-09-29T10:48:26.268Z E B_139  -     TaskUBVFileListFragments::SignalWork IPCFileLock timed out: /srv/unifi-protect/video/2025/09/29/B4FBE49F9BB9_0_rotating_1759134371289.ubv [1]
2025-09-29T10:48:26.269Z I unifi-protect  -     WorkersPool::SignalTaskFinished release task id=139 name=ubvFileListFragments inprogress 0/4 [] pending 0/200 [] [1]

**Comment by dciancu** [comment]
Please try again with the latest firmware released today.

**Comment by tszyszko** [comment]
Using inotify I can see that the files are still constantly being written to

**Comment by tszyszko** [comment]
I did a fresh install and the same thing still occurs

**Comment by dciancu** [comment]
Thanks for the updates.
I am running edge image with no issues.
Will investigate when I have the time.

**Comment by tszyszko** [comment]
No, it also fails to load

**Comment by jan-panoch** [comment]
FIXED :-)

it looks like if i downgrade msp package (Media Server Playback Service) back to 5.1.93 playback work again - even with protect version 6.1.79 (ms,msr,mst,msp version 5.1.162). Version 5.1.93 of msp is the last working version - at least by me on mac studio (m1 max cpu) with UTM + debian 13 + docker.

wget https://fw-download.ubnt.com/data/msp/aeb9-uos-deb11-arm64-5.1.93-2fed3f3a-1b06-4f29-8a1a-f611d3f4c574.deb
dpkg -i aeb9-uos-deb11-arm64-5.1.93-2fed3f3a-1b06-4f29-8a1a-f611d3f4c574.deb
dpkg: warning: downgrading msp from 5.1.162 to 5.1.93
(Reading database ... 47180 files and directories currently installed.)
Preparing to unpack aeb9-uos-deb11-arm64-5.1.93-2fed3f3a-1b06-4f29-8a1a-f611d3f4c574.deb ...
Unpacking msp (5.1.93) over (5.1.162) ...
Setting up msp (5.1.93) ...
msp postinst:[configure 5.1.162] start
msp postinst:[configure 5.1.162] enable msp.service service
msp postinst:[configure 5.1.162] stop msp.service service
msp postinst:[configure 5.1.162] restart msp.service service
msp postinst:[configure 5.1.162] msp.service restarted successfully.
msp postinst:[configure 5.1.162] end

**Comment by tszyszko** [comment]
This also fixes recordings for me, but snapshots are still broken

**Comment by dciancu** [comment]
What are the retention settings for the affected cameras?

**Comment by dciancu** [comment]
Please retry with the latest release, using Protect 7.1

**Comment by jdmhickey** [comment]
I am experiencing something similar. Playback works fine through the web interface; however, in the mobile app, historical recordings do not load and simply buffer indefinitely.

The live view can also occasionally buffer, although that is much less of an issue at the moment. Playback of recorded footage in the mobile app is currently unusable.

**Comment by dciancu** [comment]
I was never able to reproduce this issue, looking one more time i think this is an issue with the storage. But it is pretty hard to debug. If anyone is still having this issue, try checking your storage with a load test. Also check with the latest Protect release, it is more resilient.
Cameras retention settings can also cause this.
If this is still an active issue, please debug further and I'll reopen. Thanks.
