### ISSUE TITLE
Unifi Protect can't capture the available storage

### ISSUE THREAD

**Issue by gnbon** [dciancu/unifi-protect-unvr-docker-arm64#9]
I appreciate the great work on this project. While setting it up, I encountered an issue where my storage was not recognized at all. I'm currently troubleshooting this problem. I of course changed the hostname and added boot commands as well. Either if I have the wrong settings or there are any known issues related to this, please let me know.

### Environments
- Raspberry Pi 4B(Linux raspberrypi 6.6.31)
- Using external 1TB HDD(/dev/sda1)

### df -h output
- host
```
[~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            1.6G     0  1.6G   0% /dev
tmpfs           380M  1.4M  378M   1% /run
/dev/mmcblk0p2   15G  6.8G  6.6G  51% /
tmpfs           1.9G  148K  1.9G   1% /dev/shm
tmpfs           5.0M   16K  5.0M   1% /run/lock
tmpfs           4.0M     0  4.0M   0% /sys/fs/cgroup
/dev/mmcblk0p1  510M   75M  436M  15% /boot/firmware
/dev/sda1       916G  153M  870G   1% /mnt/storage
tmpfs           380M   40K  380M   1% /run/user/1000
```

- docker
```
# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          15G  6.8G  6.6G  51% /
tmpfs            64M     0   64M   0% /dev
shm              64M   56K   64M   1% /dev/shm
tmpfs           1.9G  8.3M  1.9G   1% /run
tmpfs           1.9G  1.1M  1.9G   1% /tmp
/dev/sda1       916G  152M  870G   1% /srv
tmpfs           1.9G     0  1.9G   0% /run/lock
/dev/mmcblk0p2   15G  6.8G  6.6G  51% /etc/hosts
tmpfs           4.0M     0  4.0M   0% /sys/fs/cgroup
tmpfs           1.0G     0  1.0G   0% /var/opt/unifi-protect/tmp
```

### docker-compose.yml
```
services:
  unifi-protect:
    image: dciancu/unifi-protect-unvr-docker-arm64:stable
    tty: true
    hostname: UNVR
    extra_hosts:
      - "UNVR:127.0.1.1"
    container_name: unifi-protect
    stop_grace_period: 2m
    cgroup: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /mnt/storage/srv:/srv
      - /mnt/storage/data:/data
      - /mnt/storage/persistent:/persistent
    environment:
      - container=docker
      - STORAGE_DISK=/dev/sda1
      - TZ=UTC
    restart: unless-stopped
    cap_add:
      - dac_read_search
      - sys_admin
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/run
      - /var/run/lock
    privileged: true
    network_mode: host
```
I've also attached two screenshots showing additional information. Please let me know if you need any further details or clarification on this issue.
![image](https://github.com/user-attachments/assets/009ca383-34c4-4348-9a5e-ce8aa09fde52)
![image](https://github.com/user-attachments/assets/b39acba2-7c1a-47a8-9e5c-39879f861e42)

**Comment by AnthonyOGorman** [comment]
Any update on this, I am having the same issue.

**Comment by RobBie1221** [comment]
I spent quite some time looking into this.

So far, I have the following findings with this image:
stable - Unifi is unable to capture storage
edge - Unifi is unable to capture storage
Once you connect to a doorbell it partially works. Somehow it is recording, but Protect doesn't see it is recording. The app somehow can playback video, but from a web browser it doesn't work. Big disadvantage, you can't configure e.g. smart detection zones because the web browser want's you to connect a storage. I also have problems with a smart chime continuously rebooting or reconnecting (which may or may not be related to this, anyhow the chime worked perfectly on the previous image I used from markdegroot).

What I tried, because people describe this image is actually working, to use the following tag:
UNVR4.al324.v3.2.12.7765dbb.240126.0152

The key difference is that this image runs Unifi OS v3 instead of v4. This is actually working. It comes with an old protect app, but once running you can update Protect to v4.1.53 (which works as long as you don't remove the container and re-create it).

I tried, with a working config, to update the container to the latest again, but this breaks the storage. I checked the error logs, maybe this gives a hint: 
`2024-09-13T20:01:27.307Z - error: [unvrFlashStorageMigration] Failed to check rwfs migration info via ustorage: Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at WD (file:///usr/share/unifi-core/app/service.js:197:56072)
    at Kye (file:///usr/share/unifi-core/app/service.js:197:57153)`

This whole exercise does make me wonder. I use a Raspberry Pi 4 with a clean install of Debian Bookworm, following all instructions on the main page using exactly the compose file in this repo (adjusting STORAGE_DISK).
@dciancu Did you actually test the image with Unifi OS v4? Or is there someone who can confirm this is actually working with above setup?
It makes a whole lot of difference if I try to fix something that does not work on my setup instead of fixing something that is not working at all :)

**Comment by RobBie1221** [comment]
One thing to add, looking at the dockerfile used to make this container, it seems to always use debian 11, both for containers running Unifi OS v3 and v4. Just a random thought I had, would it be possible the infrastructure of Unifi OS v4 is created around debian 12?

**Comment by Howaner** [comment]
I had the same problem with the newer versions and tried to fix it today.  
I could fix it by changing two things.

1. docker exec into your unifi protect docker container
2. Replace the two lines beginning with sbytes= and sused= to the following lines:
```
sbytes=$(df -B1 --output=size -k /srv | awk 'NR==2 {print $1}')
sbytes=$(( sbytes * 1024 ))
sused=$(df -B1 --output=used -k /srv | awk 'NR==2 {print $1}')
sused=$(( sused * 1024 ))
```
3. Open /usr/share/unifi-core/app/service.js and replace all useGrpc:!0 with useGrpc:0
4. Restart docker container

**Comment by PeterSchmidt23** [comment]
> I had the same problem with the newer versions and tried to fix it today. I could fix it by changing two things.
> 
> 1. docker exec into your unifi protect docker container
> 2. Edit /usr/bin/ustorage and replace the two lines beginning with sbytes= and sused= to the following lines:
> 
> ```
> sbytes=$(df -B1 --output=size -k /srv | awk 'NR==2 {print $1}')
> sbytes=$(( sbytes * 1024 ))
> sused=$(df -B1 --output=used -k /srv | awk 'NR==2 {print $1}')
> sused=$(( sused * 1024 ))
> ```
> 
> 3. Open /usr/share/unifi-core/app/service.js and replace all useGrpc:!0 with useGrpc:!!0
> 4. Restart docker container
> 
> I'm planning to create a merge request for it.

Good Job! I can confirm, that this is working.

**Comment by dciancu** [comment]
Check latests builds, this has been resolved.

**Comment by gigatux** [comment]
I'm still having issues with the latest edge docker image, and get the error in the storage control plane:

![Image](https://github.com/user-attachments/assets/fd1a2df1-2769-42f1-9b29-5f043a6412cb)

This is with the docker hub version v5.2.46. Do others see this as no longer working?

**Comment by dciancu** [comment]
@gigatux This is a known issue #26
